name: Repository Dispatch Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event_path }} && cat ${{ github.event_path }}
