name: Auto close and lock others issues

on:
  issues:
    types:
      - "opened"
env:
  ONWER: "tTdly-Old"

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor != env.ONWER}}
        name: CloseIssue&Lock
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actinons: "close-issue"
          token: ${{ secrets.TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: "Not accepting other people's issues. So the issue was automatically closed and locked. Thanks and good luck."
      - if: ${{ github.actor != env.ONWER}}
        name: CloseIssue&Lock
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actinons: "lock-issue"
          token: ${{ secrets.TOKEN }}
          issue-number: ${{ github.event.issue.number }}        
