name: auto close bad issue

on:
  issues:
    types:
      - "opened"

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm test

