name: Auto close and lock others issues

on:
  issues:
    types:
      - "opened"
      - "edited"
      - "closed"

env:
  INFO: ${{ toJSON(github) }}

jobs:
  logInfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: main
          fetch-depth: 0
      - run: bash ./.github/scripts/write.sh "$INFO"
      - run: cat index.md