name: Auto close and lock others issues

on:
  issues
env:
  ONWER: "tTdly-Old"

jobs:
  logInfo:
    runs-on: ubuntu-latest
    steps:
      - env:
          INFO: ${{ toJSON(github) }}
        run: echo "$INFO"