name: auto close bad issue

on:
  issues:
    types:
      - "opened"

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Run
        run: node -v && pnpm -v

