name: auto close bad issue

# on:
#   issues:
#     types:
#       - "opened"
on:
  push
env: 
  OWNER: "tTdly-Old"
  FAKE: "ttdly"
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: pnpm/action-setup@v2.2.4
      #   with:
      #     version: 7.27.0
      # - name: Cache node modules
      #   id: cache-pnpm
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.pnpm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #   name: List the state of node modules
      #   continue-on-error: true
      #   run: pnpm list

      # - name: Install dependencies
      #   run: pnpm install

      - if: ${{ github.actor != env.OWNER }}
        name: isisi
        run: echo "No"
      - if: ${{ github.actor != env.FAKE }}
        name: isisnonoi
        run: echo "YES"
        # run: node ./issue.js ""${{github.actor}}" "${{ github.event.issue.number }}" "${{ secrets.TOKEN }}"

