name: auto close bad issue

on:
  issues:
    types:
      - "opened"

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: check issue
        run: echo "${{github.actor}}" && echo "${{ github.event.issue.number }}";

