name: Caching with ppnpm
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.27.0
      - name: Cache node modules
        id: cache-pnpm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # pnpm cache files are stored in `~/.pnpm` on Linux/macOS
          path: ~/.pnpm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: pnpm list

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm -v

